FROM container-registry.oracle.com/os/oraclelinux:9

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    rm -rfv /var/cache/dnf /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:9-slim

COPY --from=0 /sbin /sbin

COPY package/COPYING THIRD_PARTY_LICENSES.txt /usr/share/licenses/
