@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/2.1.2', feature: 'feature/.*'),
  containers: ['container-registry.oracle.com/olcne/runit:2.1.2': 'olcne/runit:2.1.2'],
  platforms: ['ol8'],
    yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder']
)
