@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
  yumRepos: ['ol7_optional_latest'],
  containers: ['container-registry.oracle.com/olcne/runit:2.1.2': 'olcne/runit:2.1.2'],
  useDockerfiles: true,
  branchPattern: new BranchPattern(master: 'oracle/release/2.1.2', feature: 'feature/.*')
)
